// src/app/admin-dashboard/layout.tsx
import { Raleway } from "next/font/google";
import AdminNavbar from "./AdminNavbar";
import "../../app/globals.css"; // adjust relative path
import { Metadata } from "next";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Admin bairuha",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    // Use font-[var(--font-raleway)] to actually apply the font
    <div className={`font-[var(--font-raleway)] bg-gray-50 min-h-screen`}>
      {/* Navbar always visible */}
      <AdminNavbar />

      {/* Add padding to avoid overlap with fixed navbar */}
      <main className="pt-16">
        {children}
      </main>
    </div>
  );
}
